export const USER_KEYS = {
  SET_USER: "SET_USER",
  SET_LANGUAGE: "SET_LANGUAGE",
  ADD_ITEMS: "ADD_ITEMS",
  REMOVE_ITEMS: "REMOVE_ITEMS",
  SET_FEEDBACK: "SET_FEEDBACK",
  TOGGLE_CART: "TOGGLE_CART",
  UPDATE_TOTAL: "UPDATE_TOTAL",
};
